CC = g++
DEBUG = -g3
CFLAGS = -Wall -w --std=c++14 -c $(DEBUG)
LFLAGS = -Wall -o 

all: e1 e2 e3 e4

e1: e1.cpp
	$(CC) -o e1 e1.cpp

e2: e2.cpp
	$(CC) -o e2 e2.cpp

e3: e3.cpp
	$(CC) -o e3 e3.cpp

e4: e4.cpp
	$(CC) -o e4 e4.cpp

clean:
	\rm *.o e1 e2 e3 e4
